### ISSUE TITLE
About PSNR calculation

### ISSUE THREAD

**Issue by SwingM** [Show-han/PET-Reconstruction#8] opened 2024-03-15 02:40 UTC
I used the dataset you provided with this rep to generate 36 results, after calculating the hr and result, I found the average PSNR of results can reach 31. I noticed that in the paper published, the result is around 25-26, how this happen?

**Comment by Show-han** [comment] 2024-03-15 02:53
Duplicate of #7

**Closed** 2024-03-19 11:00 UTC
